---

- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Inclusion du vault de l'environnement
    include_vars: "{{ vault_file_path }}"
    run_once: true

- hosts: all
  become: yes
  roles:
  - k8s-python
  - k8s-docker
  - k8s-common
  - k8s-images

- hosts: master
  become: true
  roles:
  - name: k8s-master

- hosts: nodes
  become: true
  roles:
  - name: k8s-node

- hosts: master
  become: true
  roles:
  - name: k8s-secured
  - name: k8s-grafana
  - name: k8s-proxy
  - name: k8s-dashboard
