---
- name: Delete old kubernetes folder
  file:
    name: /etc/kubernetes/
    state: absent

- name: Join to K8s cluster
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ groups['master'][0] }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification
  register: join_cluster

- name: Enable and restart kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
